### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stephanieatte**
There were formatting and repeated information in the README.md , which has been updated

### CODE REVIEW

**Comment by pzeballos** [comment]
@stephanieatte you'll have to fix the merge conflicts :)

**Comment by MelissaKaulfuss** [comment]
@stephanieatte we have a monorepo plugin blog post scheduled for 4th Jan - can we get this changed merged ahead of that? 

If that's not possible @pzeballos I'll open my own PR.

**Comment by pzeballos** [comment]
> @stephanieatte we have a monorepo plugin blog post scheduled for 4th Jan - can we get this change merged ahead of that?
> 
> If that's not possible @pzeballos (due to rostering) I'll open my own PR.

Can you create a new PR @MelissaKaulfuss ? Steph is out for the holidays.

**Comment by pzeballos** [comment]
I'll close this one in favor of #6

**Pull request closed without merging**
